default:
  http_metas:
    content-type: text/html

  metas:
    title:        Journal of Computational Technologies
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    robots:       index, follow

  stylesheets:    [main]

  javascripts:    [jquery/jquery-1.3.2.min.js, layout.js]

  has_layout:     on
  layout:         layout
