<?php


/**
 * Skeleton subclass for performing query and update operations on the 'cities' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 10/17/08 12:04:15
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class cityPeer extends BasecityPeer {

	static function retrieveByName ($name)
	{
		$c = new Criteria();
		$c->add(cityPeer::NAME, $name);
        $city_obj = cityPeer::doSelectOne($c);
        if (!is_null($city_obj)) return $city_obj;
        else
        {
            $city_obj = new city();
            $city_obj->setName($name);
            $city_obj->save();
        }
        return $city_obj;
	}
} // cityPeer
