<?php


/**
 * Skeleton subclass for performing query and update operations on the 'reviews' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/01/08 09:07:52
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class reviewPeer extends BasereviewPeer {
    const UNREVIEWED    = 0;
    const ACCEPT        = 1;
    const ACCEPT_SMALL  = 4;
    const ACCEPT_COMMENT= 5;
    const REVISE        = 2;
    const REJECT        = 3;
    const REFUSED_REVIEW= 6;

    public static function outcomeString ($v)
    {
    	$string ='';
        switch ($v)
        {
        	case self::UNREVIEWED:     $string = 'Unreviewed'; break;
        	case self::ACCEPT:         $string = 'Accept as is'; break;
        	case self::ACCEPT_COMMENT: $string = 'Send to authors for major rework'; break;
        	case self::ACCEPT_SMALL:   $string = 'Accept after minor improvements'; break;
        	case self::REVISE:         $string = 'Rewrite and submit as brief communication'; break;
        	case self::REJECT:         $string = 'Reject'; break;
        	case self::REFUSED_REVIEW: $string = manuscriptPeer::statusString(manuscriptPeer::REVIEWER_REFUSED); break;
        }
        return $string;
    }
    
    /**
     * Returns review form
     * Implements factory pattern
     * @param $obj review object for form
     * @return $form form object descending from ReviewBaseForm
     */
    public static function getForm (review $obj)
    {
    	$class = sfConfig::get('app_review_class');
    	$form = new $class($obj);
    	if (!($form instanceof ReviewBaseForm))
    	   throw new LogicException(sprintf("%s must inherit from ReviewBaseForm", $class));
    	if (!$form->getWidget('recommend'))
           throw new LogicException(sprintf("%s must have \"recommend widget", $class));
        return $form;
    }
    
}
