<?php


/**
 * Skeleton subclass for representing a row from the 'reviews' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/01/08 09:07:53
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class review extends Basereview {

	/**
	 * Initializes internal state of review object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

	public function setOutcome($v, $time = null)
	{
		if ($time != null) $this->setSubmitted($time);
		else $this->setSubmitted (time());
		parent::setOutcome($v);
	}
	
	public function getOutcomeString()
	{
		return reviewPeer::outcomeString($this->getOutcome());
	}

    public function getFilename()
    {
        $filename =  'r_'.$this->getManuscriptId().'_'.$this->getUserId().'_0';
        $files = sfFinder::type('file')->name($filename.'*')->maxdepth(1)->in(sfConfig::get('sf_upload_dir'));
        if (count($files)>1) throw new sfException('duplicate manuscript files', 100);
        if (count($files) == 0) return null;
        return $files[0];
    }
	
} // review
