<?php


/**
 * Skeleton subclass for performing query and update operations on the 'users_manuscripts_ref' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/04/08 19:00:18
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class userManuscriptRefPeer extends BaseuserManuscriptRefPeer {

} // userManuscriptRefPeer
