<?php


/**
 * Skeleton subclass for representing a row from the 'users_manuscripts_ref' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * 11/04/08 19:00:18
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class userManuscriptRef extends BaseuserManuscriptRef {

	/**
	 * Initializes internal state of userManuscriptRef object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}

} // userManuscriptRef
