prod:
  propel:
    class:          sfPropelDatabase
    param:
      classname:          PropelPDO     

all:
  propel:
    class:          sfPropelDatabase
    param:
      classname:          DebugPDO
      dsn:                mysql:dbname=abajour;host=localhost
      username:           root
      password:           sw1eGJgLxJ
      encoding:           utf8      # Default charset for table creation
      persistent:         true      # Use persistent connections
      pooling:            true
      
